### PR TITLE
Update for token movement

### PR DESCRIPTION
**Pull request by erithtotl**
Implemented functionality so tokens can move over and under walls, after  checking elevation and wall height.

Also added a macro for quickly setting elevation for multiple tokens.

To do:  A configuration screen to turn off or on movement function (right now always on).

### CODE REVIEW

**Comment by schultzcole** [comment]
Hi @erithtotl. Thank you for the pull request, but I do not intend to merge it, because I am not actively supporting wall height at this time.

If you wish, I could facilitate transferring ownership of the Wall Height module in the foundry package listing to you for you to officially release these changes and support Wall Height going forward.

**Comment by erithtotl** [comment]
I'd be willing to take over the module.

**Comment by schultzcole** [comment]
Ok, I will start the transfer process

**Comment by schultzcole** [comment]
Ok @erithtotl, I'm not sure if he's told you or not, but Nath has transferred ownership of the wall height package to you. If you go to https://foundryvtt.com/admin/ while signed into your account, you should be able to see the package details and add a new release that points to your repo once you have it all set up.

**Comment by erithtotl** [comment]
Thanks for the update, so I should just reference my fork from now on?

**Comment by schultzcole** [comment]
Yep, just change the urls in the module.json to point to your fork.

By the way, this repo is designed with the following release workflow in mind (though of course you are free to use whatever workflow you prefer). This workflow makes use of github tag archives to serve content to the users for a specific release number.

1. Make changes on the `develop` branch.
2. When all changes for a given release have been made, edit the changelog to reflect them
3. Modify the manifest (module.json) to point to the new version (i.e. if the new version is X.Y.Z, find and replace the old version number in module.json with X.Y.Z). The new version number should be changed in the `version` key as well as the `download`, `license`, `readme`, and `changelog` keys.
4. Push changes to develop.
5. Switch to master, then merge `develop` into `master`.
6. Add a git tag for the new version. This is the appropriate git cli command: `git tag -a X.Y.Z -m "X.Y.Z"`
7. Push to master, including tags: `git push --follow-tags`
8. On the github repo homepage, click on "tags" (should be near the center of the page just below the "Code", "Issues", "Pull Requests", etc. tabs)
9. On the tags page, click on the 3 dots icon for the new tag you just pushed, then choose the option to add a new release. I usually just name the release "Version X.Y.Z" and put a link to the changelog, then submit the release.
10. In the foundry package admin page for the module, all the way at the bottom, add a new entry for the latest release, using the appropriate archive link for the newly created tag. Also keep in mind that the manifest/module.json link *must* be the raw link, like so: `https://raw.githubusercontent.com/schultzcole/FVTT-Wall-Height/3.0.1/module.json`
11. When you save the foundry package listing after adding a new release entry, it will *automatically* make a post in the #release-announcements channel in discord. I usually like to follow up that post with a summary of the changes.

I think that's basically the process I use, hopefully that is helpful for you.

Also, when you change the links in the module.json to point to your fork, the built in Foundry update method may not catch that a switch was made to a new repo, so users *may* need to uninstall and reinstall the module to get your version the first time they update. I'll see what I can do to mitigate that as much as possible.

**Comment by erithtotl** [comment]
Hi Cole,

Just getting around to publishing my first release.  While I see I am
listed as the owner of the module on the module page (
https://foundryvtt.com/packages/wall-height/), and it is indeed me, I don't
see any option to access an admin page?  Do I perhaps have to email the
admins on the website to get this turned on, or is there some secret url?

**Comment by schultzcole** [comment]
You *should* be able to go to https://foundryvtt.com/admin/ and sign in there. If you're not able to, then you should send them an email.

**Comment by erithtotl** [comment]
Yup no access I'll contact them.

**Pull request closed without merging**
